logging.level:
  org.springframework.security.web.contex.HttpSessionSecurityContextRepository: debug

server:
  port: 8083

# Actuator/Security configuration

endpoints:
  sensitive: true  # protect all endpoints
  health:
    sensitive: false # unprotected
  security:
    role: SYS_ADMIN    

# Application configuration
login.url: /
   

spring:
  profiles:
    active: customAuth
         
---
spring:
  profiles: dev    
  thymeleaf:
    cache: false
    
---
spring:
  profiles: preAuth    

# Pre-Authentication configuration. Sets up the user we want to use and its roles without having to manually login    
preAuth:
  username: joe
  credential: password
  roles: USER, SYS_ADMIN
  organization: joeOrg
  
    
    
    